image: docker:latest
services:
  - docker:dind
stages:
  - build
  - deploy
variables:
  DOCKER_HOST: tcp://docker:2375  # Set the Docker daemon host for Docker-in-Docker
  DOCKER_TLS_CERTDIR: ""          # Disable TLS for Docker-in-Docker, as TLS is not used by default here
before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  - echo $CI_REGISTRY
  - echo $CI_REGISTRY_IMAGE
build:
  stage: build
  script:
    - docker build --no-cache -t $CI_REGISTRY_IMAGE .
    - docker --debug push $CI_REGISTRY_IMAGE
    


deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client docker-cli
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | sed 's/\r$//' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan jowin.at >> ~/.ssh/known_hosts
  script:
    - ssh -tt -o StrictHostKeyChecking=no deploy@jowin.at "cd /home/deploy/chat/ &&  docker-compose down &&  docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD &&  docker image rm registry.jowin.at/jowin202/webfix:latest -f || true && docker-compose up -d"
      
